# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f41c8c7cf58c7f2ab685aec081854fea004747de408d0ee0623d77134d74ea4ce7d84daa3a92c247b100b95346f66c1a033baf4de8022c0887878a97320fc6df

test:
  secret_key_base: 46a3aacc52aeb4897650fa5a9f7b0fb48433f9054f0b2f29871b2a0ffb37fc3c3e9b576b7c764ff327d2b3a1d2d1dcb900e0c38e2414d2252e2bba6c0d8a56d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
